CREATE TABLE [dbo].[Song] (
    [SongKey]                     INT              IDENTITY (1, 1) NOT NULL,
    [Custom]                      BIT              NOT NULL,
    [AuthorKey]                   INT              NOT NULL,
    [SongId]                      VARCHAR (200)    NOT NULL,
    [Title]                       VARCHAR (60)     NOT NULL,
    [Artist]                      VARCHAR (50)     NOT NULL,
    [KoreographyKey]              INT              NOT NULL,
    [Descriptor]                  VARCHAR (50)     NOT NULL,
    [SceneName]                   VARCHAR (50)     NOT NULL,
    [AvgBpm]                      DECIMAL (18, 15) NOT NULL,
    [BeatDivisions]               VARCHAR (200)    NOT NULL,
    [TempoSections]               VARCHAR (MAX)    NOT NULL,
    [SongEventTracks]             VARCHAR (MAX)    NOT NULL,
    [SongURL]                     VARCHAR (200)    NOT NULL,
    [FirstBeatTimeInSeconds]      DECIMAL (18, 15) NOT NULL,
    [SongEndTimeInSeconds]        DECIMAL (18, 14) NOT NULL,
    [SongShortStartTimeInSeconds] DECIMAL (5, 1)   NOT NULL,
    [SongShortStopTimeInSeconds]  DECIMAL (5, 1)   NOT NULL,
    [LeadingSilenceSeconds]       DECIMAL (5, 1)   NOT NULL,
    [SongFullLengthInSeconds]     DECIMAL (18, 14) NOT NULL,
    [SongShortLengthInSeconds]    DECIMAL (5, 1)   NOT NULL,
    [SongStartFadeTime]           DECIMAL (5, 1)   NOT NULL,
    [SongEndFadeTime]             DECIMAL (5, 1)   NOT NULL,
    [PreviewStartInSeconds]       DECIMAL (5, 1)   NOT NULL,
    [PreviewDurationInSeconds]    DECIMAL (5, 1)   NOT NULL,
    [SongStartBufferInSeconds]    DECIMAL (5, 1)   NOT NULL,
    [ChoreoJsons]                 VARCHAR (MAX)    NOT NULL,
    [AnimClips]                   VARCHAR (MAX)    NOT NULL,
    [Speed]                       DECIMAL (5, 1)   NOT NULL,
    [QuantizeSize]                DECIMAL (18, 15) NOT NULL,
    [IncludeInArcades]            BIT              NOT NULL,
    [SupportedModalitySets]       INT              NOT NULL,
    [DrumMedSfx]                  VARCHAR (50)     NOT NULL,
    [DrumMaxSfx]                  VARCHAR (50)     NOT NULL,
    [GenreKey]                    INT              NOT NULL,
    [Description]                 VARCHAR (400)    NOT NULL,
    [Explicit]                    BIT              NOT NULL,
    [Challenge]                   BIT              NOT NULL,
    [ContentStrike]               BIT              NOT NULL,
    [Released]                    DATETIME         NOT NULL,
    CONSTRAINT [PK_Song] PRIMARY KEY CLUSTERED ([SongKey] ASC),
    CONSTRAINT [FK_Song_Song] FOREIGN KEY ([SongKey]) REFERENCES [dbo].[Song] ([SongKey])
);

